# Generated by Django 3.0.6 on 2020-05-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='paragraph',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
