# Generated by Django 3.0.6 on 2020-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_compiler', '0002_auto_20200522_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
