# Generated by Django 3.0.6 on 2020-05-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_compiler', '0003_auto_20200523_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='class_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='task',
            name='paragraph',
            field=models.IntegerField(default=0, verbose_name='Номер параграфа'),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Код (создается автоматически)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, null=True, verbose_name='Текст задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.CharField(max_length=30, verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_snippet',
            field=models.TextField(blank=True, null=True, verbose_name='Предопределенный фрагмент кода'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
