# Generated by Django 3.0.6 on 2020-05-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_compiler', '0005_auto_20200523_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='class_homework',
            field=models.CharField(choices=[('lesson', 'Задача с уроков'), ('homework', 'Упражнение для самостоятельного решения')], default='lesson', max_length=255, verbose_name='Тип задания'),
        ),
    ]
