# Generated by Django 3.0.6 on 2020-05-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_compiler', '0007_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='paragraph_id',
            field=models.IntegerField(verbose_name='Номер параграфа'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название параграфа'),
        ),
    ]
