# Generated by Django 3.0.6 on 2020-05-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_compiler', '0010_auto_20200524_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragraph',
            options={'verbose_name': 'Параграф', 'verbose_name_plural': 'Параграфы'},
        ),
    ]
